name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run Dagger pipeline
      uses: dagger/dagger-for-github@v6
      with:
        version: "latest"
        verb: call
        args: test --source=.
        
    - name: Generate and export demo gif
      run: |
        dagger call generate-demo-gif --source=. export --path=./demo.gif
        mkdir -p ./artifacts
        mv ./demo.gif ./artifacts/
        
    - name: Upload demo gif artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: tmux-buffer-sync-demo
        path: ./artifacts/
        retention-days: 30
